spring:
  application:
    name: ead-notification-api
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configServer
      password: ${CONFIG_SERVER_PASSWORD}